experiment:
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/ratings.dat
#    root_folder: ../data/{0}/splitting/
    side_information:
      - dataloader: KGRec
        mapping: ../data/{0}/mapping.tsv
        kg_train: ../data/{0}/kg_train.tsv
        kg_dev: ../data/{0}/kg_valid.tsv
        kg_test: ../data/{0}/kg_test.tsv
  splitting:
#    save_on_disk: True
#    save_folder: ../data/{0}/splitting/
    test_splitting:
        strategy: temporal_hold_out
        test_ratio: 0.2
  dataset: ml1m_ktup
  external_models_path: ../external/models/__init__.py
#  print_results_as_triplets: True
  top_k: 10
#  config_test: True
  evaluation:
    cutoffs: [10, 5]
    simple_metrics: [nDCG, Precision, Recall, ItemCoverage, HR, MAP, F1, Gini, SEntropy]
    relevance_threshold: 3
#    paired_ttest: True
#    wilcoxon_test: True
#    complex_metrics:
#    - metric: ExtendedF1
#      metric_0: Precision
#      metric_1: Recall
  gpu: 1 # -1 is not use GPU
  models:
    external.KTUP:
      meta:
        hyper_max_evals: 1
        hyper_opt_alg: tpe
        validation_rate: 1
        verbose: False
        save_weights: False
        save_recs: False
#        restore: True
      epochs: 10
      batch_size: 10
#    MultiVAE:
#      meta:
#        hyper_max_evals: 20
#        hyper_opt_alg: tpe
#        validation_rate: 1
#        verbose: False
#        save_weights: False
#        save_recs: False
##        restore: True
#      lr: [loguniform, -10, -1]
#      epochs: 10
#      intermediate_dim: [uniform,50,300]
#      latent_dim: [uniform,50,300]
#      batch_size: -1
#      dropout_pkeep: 1
#      reg_lambda: [0, 0.01]