experiment:
  dataset: yahoo_movies
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/dataset.tsv
    # test_path: ../data/{0}/testset.tsv
    side_information:
      - dataloader: KGFlexLoader
        mapping: ../data/{0}/mapping.tsv
        kg_train: ../data/{0}/kg_train.tsv
        second_hop: ../data/{0}/kg_train_2hop.tsv
        properties: ../data/{0}/properties.conf
        additive: True
  prefiltering:
    strategy: iterative_k_core
    core: 10
  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  top_k: 10
  # gpu: 0
  external_models_path: ../external/models/__init__.py
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCGRendle2020, nDCG, HR, Precision, ItemCoverage]
    relevance_threshold: 3
  models:
    external.KGFlexTF:
      meta:
        verbose: True
        validation_rate: 5
        save_recs: True
        save_weights: False
        restore: False
        hyper_max_evals: 10
        hyper_opt_alg: tpe
      seed: 42
      lr: [loguniform, -11.512925464970229, 0]
      # lr: 0.001
      epochs: 50
      batch_size: [8, 16, 32, 64, 128, 256]
      # batch_size: 128
      embedding: [64, 128, 256]
      # embedding: 256
      first_order_limit: [100, 200, 300]
      second_order_limit: [100, 200, 300]
      loader: KGFlexLoader
