experiment:
  dataset: yahoo
  data_config:
    strategy: fixed
    train_path: ../data/{0}/trainingset.tsv
    test_path: ../data/{0}/testset.tsv
    side_information:
      - dataloader: KGFlexLoader
        mapping: ../data/{0}/mapping.tsv
        kg_train: ../data/{0}/kg_train.tsv
        second_hop: ../data/{0}/kg_train_2hop.tsv
        properties: ../data/{0}/properties.conf
        additive: True
  prefiltering:
    strategy: iterative_k_core
    core: 5
  top_k: 10
  gpu: 1
  external_models_path: ../external/models/__init__.py
  evaluation:
    cutoffs: [10,9,8,7,6,5,4,2,1]
    simple_metrics: [nDCGRendle2020, nDCG, HR, Precision, Recall, MAP, MRR, ItemCoverage, UserCoverage, NumRetrieved, UserCoverage, Gini, SEntropy, EFD, EPC]
  models:
    external.KGFlex:
      meta:
        verbose: True
        validation_rate: 10
        save_recs: True
        save_weights: True
        restore: False
      seed: 42
      lr: [0.1, 0.01, 0.001]
      epochs: 200
      batch_size: 128
      embedding: [10]
      first_order_limit: [0, 10, 100]
      second_order_limit: [0, 10, 100]
      loader: KGFlexLoader
