experiment:
  dataset: lastfm_1k
  data_config:
    strategy: fixed
    train_path: ../data/lastfm_1k/filtered_data/0/train.tsv
    test_path: ../data/lastfm_1k/filtered_data/0/test.tsv
  top_k: 50
  path_output_rec_result: ./results/lastfm_1k_item_ed_rep/recs/
  path_output_rec_weight: ./results/lastfm_1k_item_ed_rep/weights/
  path_output_rec_performance: ./results/lastfm_1k_item_ed_rep/performance/
  path_log_folder: ../log/lastfm_1k_item_ed_rep/
  evaluation:
    cutoffs: [10] #[ 1,5,10,20 ]
    simple_metrics: [ ACLT ]
  gpu: 0
  models:
    RecommendationFolder:
        folder: ./results/lastfm_1k_item_ed_rep/recs/